import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Hero from "../components/Hero";
import History from "@/components/History";
import Info from "@/components/Info";
import Footer from "@/components/Footer";
import Attendance from "@/components/Attendance";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <div>
      <Head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="anonymous"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Marck+Script&family=Raleway:wght@100;200;300;600&display=swap"
          rel="stylesheet"
        />
        <title>H&S</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero />
      <History />
      <Info />
      <Attendance />
      <Footer />
    </div>
  );
}
